
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Hasta = 49;
  public static final int Para = 42;
  public static final int Mod = 81;
  public static final int FinMientras = 46;
  public static final int Menor = 72;
  public static final int Coma = 22;
  public static final int FinSi = 36;
  public static final int DeloContrario = 37;
  public static final int Comilla = 59;
  public static final int Char = 80;
  public static final int Booleano = 63;
  public static final int ConParametros = 53;
  public static final int FinPara = 43;
  public static final int Segun = 39;
  public static final int DosPuntos = 67;
  public static final int Else = 4;
  public static final int Resta = 8;
  public static final int FinFuncion = 27;
  public static final int Int = 2;
  public static final int OperadorNot = 69;
  public static final int finAnalisis = 30;
  public static final int Numeroo = 25;
  public static final int Suma = 7;
  public static final int Osi = 38;
  public static final int Mientras = 45;
  public static final int OperadorOr = 64;
  public static final int OperadorRelacional = 86;
  public static final int FinSegun = 41;
  public static final int ERROR = 28;
  public static final int Imprimir = 55;
  public static final int Cadena = 65;
  public static final int MenorIgual = 79;
  public static final int String = 78;
  public static final int Main = 20;
  public static final int Repetir = 47;
  public static final int Caracter = 85;
  public static final int TipoCadena = 66;
  public static final int Ejecutar = 54;
  public static final int Asignar = 77;
  public static final int Entonces = 35;
  public static final int ParentesisC = 17;
  public static final int ParentesisA = 16;
  public static final int Car = 60;
  public static final int LlaveC = 19;
  public static final int GuionLow = 61;
  public static final int LlaveA = 18;
  public static final int inicioAnalisis = 29;
  public static final int Mayor = 73;
  public static final int If = 3;
  public static final int Flotante = 82;
  public static final int MayorIgual = 83;
  public static final int EOF = 0;
  public static final int Retornar = 50;
  public static final int Ingresar = 31;
  public static final int Numero = 24;
  public static final int Metodo = 51;
  public static final int Double = 75;
  public static final int Division = 15;
  public static final int Falso = 12;
  public static final int Funcion = 26;
  public static final int PuntoComa = 21;
  public static final int Verdadero = 11;
  public static final int error = 1;
  public static final int Potencia = 56;
  public static final int Float = 84;
  public static final int HastaQue = 48;
  public static final int Identificador = 23;
  public static final int Hacer = 40;
  public static final int ConIncremental = 44;
  public static final int OperadorLogico = 10;
  public static final int Modulo = 57;
  public static final int InterrogacionC = 14;
  public static final int OperadorAnd = 74;
  public static final int InterrogacionA = 13;
  public static final int CorcheteC = 71;
  public static final int IgualIgual = 76;
  public static final int CorcheteA = 62;
  public static final int FinMetodo = 52;
  public static final int Igual = 6;
  public static final int Doble = 70;
  public static final int While = 5;
  public static final int ConValor = 33;
  public static final int Si = 34;
  public static final int Multiplicacion = 9;
  public static final int Boolean = 68;
  public static final int ImprimirSalto = 58;
  public static final int Como = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Int",
  "If",
  "Else",
  "While",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "OperadorLogico",
  "Verdadero",
  "Falso",
  "InterrogacionA",
  "InterrogacionC",
  "Division",
  "ParentesisA",
  "ParentesisC",
  "LlaveA",
  "LlaveC",
  "Main",
  "PuntoComa",
  "Coma",
  "Identificador",
  "Numero",
  "Numeroo",
  "Funcion",
  "FinFuncion",
  "ERROR",
  "inicioAnalisis",
  "finAnalisis",
  "Ingresar",
  "Como",
  "ConValor",
  "Si",
  "Entonces",
  "FinSi",
  "DeloContrario",
  "Osi",
  "Segun",
  "Hacer",
  "FinSegun",
  "Para",
  "FinPara",
  "ConIncremental",
  "Mientras",
  "FinMientras",
  "Repetir",
  "HastaQue",
  "Hasta",
  "Retornar",
  "Metodo",
  "FinMetodo",
  "ConParametros",
  "Ejecutar",
  "Imprimir",
  "Potencia",
  "Modulo",
  "ImprimirSalto",
  "Comilla",
  "Car",
  "GuionLow",
  "CorcheteA",
  "Booleano",
  "OperadorOr",
  "Cadena",
  "TipoCadena",
  "DosPuntos",
  "Boolean",
  "OperadorNot",
  "Doble",
  "CorcheteC",
  "Menor",
  "Mayor",
  "OperadorAnd",
  "Double",
  "IgualIgual",
  "Asignar",
  "String",
  "MenorIgual",
  "Char",
  "Mod",
  "Flotante",
  "MayorIgual",
  "Float",
  "Caracter",
  "OperadorRelacional"
  };
}

